version: "3"

services:
  springapp:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - springdb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/polls?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: pass

  springdb:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mesghal
      MYSQL_USER: username
      MYSQL_PASSWORD: secretpass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: